query info {
  info {
    id
    version
    name
    description
  }
}

fragment FileInfoFragment on FileInfo {
  id
  name
  mimeType
  externalId
  assetIds
  labels
}

query all_files {
  fileInfos {
    ...FileInfoFragment
  }
}
query files_by_mimeType {
  fileInfos(filter: { mimeType: "application/pdf" }) {
    ...FileInfoFragment
  }
}

query files_by_name {
  fileInfos(filter: { name: "PH-ME-P-0156-001.pdf" }) {
    ...FileInfoFragment
  }
}

query files_by_assets {
  fileInfos(
    filter: { assetIds: [702630644612, 8790823573167638, 853289072917784] }
  ) {
    ...FileInfoFragment
  }
}

query fileLinks {
  fileLinks(ids: [{ id: 748012071562569 }]) {
    id
    url
  }
}

fragment AssetFragment on Asset {
  id
  rootId
  parentExternalId
  externalId
  name
  parentId
  childCount
  depth
  path {
    id
  }
  description
  dataSetId
  metadata {
    id
    value
  }
  source
  labels
  lastUpdatedTime
  createdTime
}

query all_assets {
  assets {
    ...AssetFragment
  }
}

query asset_name_filter {
  assets(scope: { filter: { name: "23-TT-92539" } }) {
    ...AssetFragment
  }
}

query retrieve_assets {
  retrieve(id: "6687602007296940") {
    ...AssetFragment
  }
}

fragment TimeseriesFragment on Timeseries {
  id
  externalId
  name
  isString
  metadata {
    id
    value
  }
  unit
  assetId
  dataSetId
  isStep
  description
  securityCategories
  lastUpdatedTime
  createdTime
}

query all_timeseries {
  timeseries {
    ...TimeseriesFragment
  }
}

query timeseries_for_asset {
  timeseries(
    scope: { filter: { assetIds: [6079953337268935] } }
  ) {
    ...TimeseriesFragment
  }
}

query all_aggregates {
  aggregates {
    id
  }
}

fragment DatapointAggregateFragment on DatapointAggregate {
  id
  timestamp
  average
  max
  min
  count
  sum
  interpolation
  stepInterpolation
  totalVariation
  continuousVariance
  discreteVariance
}

query datapoints_aggregates {
  datapoints(
    filter: {
      items: [
        {
          externalId: "pi:160031"
          aggregates: [
            "average"
            "max"
            "min"
            "count"
            "sum"
            "interpolation"
            "stepInterpolation"
            "totalVariation"
            "continuousVariance"
            "discreteVariance"
          ]
          granularity: "m"
        }
      ]
    }
  ) {
    id
    datapointAggregates {
      id
      externalId
      isStep
      isString
      unit
      datapoints {
        ...DatapointAggregateFragment
      }
    }
  }
}

query datapoints {
  datapoints(filter: { items: [{ id: 643849686863640 }] }) {
    datapoints {
      id
      externalId
      isStep
      isString
      unit
      doubleDatapoints {
        timestamp
        value
      }
      stringDatapoints {
        timestamp
        value
      }
    }
  }
}
